apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockv1depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockv1
  template:
    metadata:
      labels:
        app: stockv1
    spec:
      containers:
      - name: stockv1-container
        image: omkadam/stockimg:v1
        ports:
        - containerPort: 3000
